# Copyright 2025 Alejandro de Cock Buning; Ivan Vidal; Francisco Valera; Diego R. Lopez.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


---
apiVersion: v1
kind: Namespace
metadata:
  name: l2sm-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: l2smdns-dns-sa
  namespace: l2sm-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: l2smdns-config-editor
  namespace: l2sm-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: l2smdns-coredns-config-editor-binding
  namespace: l2sm-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: l2smdns-config-editor
subjects:
- kind: ServiceAccount
  name: l2smdns-dns-sa
  namespace: l2sm-system
---
apiVersion: v1
data:
  Corefile: ".:53 {\n      errors\n      health {\n        lameduck 5s\n      }\n
    \     hosts {\n        10.0.0.1 test-pod.test-network.global.l2sm\n        fallthrough\n
    \     } \n      ready\n      forward . /etc/resolv.conf\n      cache 30\n      loop\n
    \     reload\n      loadbalance\n  }"
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: l2sm-coredns
    kubernetes.io/name: l2sm-coredns
  name: l2smdns-coredns-config
  namespace: l2sm-system
---
apiVersion: v1
kind: Service
metadata:
  name: l2smdns-service
  namespace: l2sm-system
spec:
  ports:
  - name: dns
    nodePort: 30053
    port: 53
    protocol: UDP
  - name: dns-tcp
    nodePort: 30053
    port: 53
    protocol: TCP
  - name: updater
    nodePort: 30808
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    k8s-app: l2sm-coredns
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: l2sm-coredns
    app.kubernetes.io/instance: l2sm-coredns
    app.kubernetes.io/name: l2sm-coredns
    app.kubernetes.io/version: 1.12.0
    k8s-app: l2sm-coredns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: l2sm-coredns
  name: l2smdns-coredns
  namespace: l2sm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: l2sm-coredns
      app.kubernetes.io/name: l2sm-coredns
      k8s-app: l2sm-coredns
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/config: 58efddd4e9f9e69d52c550642f3dcd7d47ce558e843fddf6aa5b42face545395
      labels:
        app.kubernetes.io/instance: l2sm-coredns
        app.kubernetes.io/name: l2sm-coredns
        k8s-app: l2sm-coredns
    spec:
      containers:
      - env:
        - name: CONFIGMAP_NS
          value: l2sm-system
        - name: CONFIGMAP_NAME
          value: l2smdns-coredns-config
        image: alexdecb/l2smdns-grpc:1.0
        name: dns-server
        ports:
        - containerPort: 8081
      - args:
        - -conf
        - /etc/coredns/Corefile
        image: coredns/coredns:1.12.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 5
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: coredns
        ports:
        - containerPort: 53
          name: udp-53
          protocol: UDP
        - containerPort: 53
          name: tcp-53
          protocol: TCP
        - containerPort: 9153
          name: tcp-9153
          protocol: TCP
        readinessProbe:
          failureThreshold: 5
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
        - mountPath: /etc/coredns
          name: config-volume
      dnsPolicy: Default
      serviceAccountName: l2smdns-dns-sa
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      volumes:
      - configMap:
          items:
          - key: Corefile
            path: Corefile
          name: l2smdns-coredns-config
        name: config-volume
