
apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-config
  labels:
    app.kubernetes.io/name: l2sm-coredns
    kubernetes.io/name: "l2sm-coredns"
data:
  Corefile: |
    .:53 {
          errors
          health {
            lameduck 5s
          }
          hosts {
            10.0.0.1 test-pod.test-network.global.l2sm
            fallthrough
          } 
          ready
          forward . /etc/resolv.conf
          cache 30
          loop
          reload
          loadbalance
      }