apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: NodePort
  ports:
  - name: dns
    port: 53
    protocol: UDP
    nodePort: 30053
  - name: dns-tcp
    port: 53
    nodePort: 30053